server:
  port: 8764
spring:
  datasource:
    url: jdbc:mysql://192.168.10.129:3306/cloud_user?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: zks123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      server-addr: 120.24.38.249:8848

mybatis:
  type-aliases-package: com.gzhu.pojo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/*.xml

