server:
  port: 8763
spring:
  datasource:
    url: jdbc:mysql://192.168.10.129:3306/cloud_order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: zks123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderservice
  rabbitmq:
    host: 192.168.10.129
    port: 5672
    username: itcast
    password: 123321
    virtual-host: /
  cloud:
    nacos:
      server-addr: 192.168.10.129:8848


mybatis:
  type-aliases-package: com.gzhu.pojo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/*.xml






